# Generated by Django 4.2.1 on 2024-02-27 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_service_description_en_service_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{1,4} \\d{1,15}$|^(\\+\\d{1,4}\\d{1,15})$')]),
        ),
    ]
