# Generated by Django 4.2.1 on 2024-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='image',
            field=models.ImageField(upload_to='views/'),
        ),
    ]
